[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."dart-proxy"]
  external_node_modules = []

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
